### ISSUE TITLE
[Feature]: Persistent snackbar

### ISSUE THREAD

**Issue by Apollo108** [feduke-nukem/flutter_easy_dialogs#19]
### What is your idea?

I didn't see an option like: 'autoHide'. How to make a snackbar to stay until I hide it manually besides setting **autoHideDuration: const Duration(days: 999)**?

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by feduke-nukem** [comment]
> ### What is your idea?
> I didn't see an option like: 'autoHide'. How to make a snackbar to stay until I hide it manually?
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

Hello @Apollo108.

Thanks for a issue.

There is a property named `autoHideDuration` and if you pass `null`, it won't do the auto hide thing, so later you could hide dialog manually:

```dart
Container(
  color: Colors.blueAccent,
  width: double.infinity,
  height: 200.0,
  child: const Text('Hello World'),
).positioned(autoHideDuration: null).show();
```
or
```dart
FlutterEasyDialogs.show(
  EasyDialog.positioned(
    autoHideDuration: null,
    content: Container(
      color: Colors.blueAccent,
      width: double.infinity,
      height: 200.0,
      child: const Text('Hello World'),
    ),
  ),
);
```

**Comment by feduke-nukem** [comment]
> Thanks for quick response, it works, despite being not so obvious)

Will update documentation for that case later 😄
