### ISSUE TITLE
[Question]: How to make a dialog swipeable?

### ISSUE THREAD

**Issue by Apollo108** [feduke-nukem/flutter_easy_dialogs#21]
### What is your question?

I'm trying to make a snackbar with 3 sec auto hide, + I need it to be able to swipe it away at any time. Didn't find a way to do this, please, help.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by feduke-nukem** [comment]
> ### What is your question?
> I'm trying to make a snackbar with 3 sec auto hide, + I need it to be able to swipe it away at any time. Didn't find a way to do this, please, help.
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

Hello @Apollo108.

```dart
import 'package:flutter/material.dart';
import 'package:flutter_easy_dialogs/flutter_easy_dialogs.dart';

void main() => runApp(const MainApp());

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      builder: FlutterEasyDialogs.builder(),
      home: Scaffold(
        body: const Center(
          child: Text('Hello World!'),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () => Container(
            color: Colors.red,
            height: 200,
            width: double.infinity,
          )
              .positioned(autoHideDuration: const Duration(seconds: 3))
              .swipe()
              .slideHorizontal()
              .show(),
        ),
      ),
    );
  }
}
```

Try this

**Comment by Apollo108** [comment]
Thanks. But I also need to bind onHide and onShow callbacks, I found it possible via EasyDialogDecoration.builder, but I noticed that onHide doesn't trigger when I'm swiping it out, but the onDismiss does, so, in the end, it's working like this:
<img width="738" alt="image" src="https://github.com/feduke-nukem/flutter_easy_dialogs/assets/16933202/3a54a6bb-1f01-4174-9dc4-9553115821b6">

Please, correct me, if I'm doing it wrong.

**Comment by Apollo108** [comment]
Also I need the `onTap` callback, but I didn't find it. Can I avoid wrapping it in GestureDetector?)

**Comment by Apollo108** [comment]
Also, I noticed strange behavior for top-positioned dialogs - I have to add `direction: position == EasyDialogPosition.top ? VerticalSlideDirection.down : VerticalSlideDirection.up`, otherwise it will be sliding from the bottom (by default) during the appearance and hiding, and it looks weird. For bottom-positioned - it's fine

**Comment by feduke-nukem** [comment]
> Thanks. But I also need to bind onHide and onShow callbacks, I found it possible via EasyDialogDecoration.builder, but I noticed that onHide doesn't trigger when I'm swiping it out, but the onDismiss does, so, in the end, it's working like this: <img alt="image" width="723" src="https://user-images.githubusercontent.com/16933202/264984141-896dbd5c-0f3e-48e9-b9e1-6fbb8bfd8141.png">
> 
> Please, correct me, if I'm doing it wrong.

You may use `onHidden` callback that is called when dialog is no longer presented. `onHide` doesn't fire in your case, because it's being removed via `Dismissible` which has it's own animation and lifecycle. 

> Also I need the onTap callback, but I didn't find anything similar. Can I avoid wrapping it in GestureDetector?)

You can add `.tap()` decoration:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_easy_dialogs/flutter_easy_dialogs.dart';

void main() => runApp(const MainApp());

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      builder: FlutterEasyDialogs.builder(),
      home: Scaffold(
        body: const Center(
          child: Text('Hello World!'),
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () => Container(
            color: Colors.red,
            height: 200,
            width: double.infinity,
          )
              .positioned(autoHideDuration: const Duration(seconds: 3))
              .swipe()
              .tap(
                onDismissed: () => print('tapped'),
              )
              .slideHorizontal()
              .decorate(
                EasyDialogDecoration.builder(
                  (context, dialog) => dialog.content,
                  onHidden: () {
                    print('');
                  },
                ),
              )
              .show(),
        ),
      ),
    );
  }
}
```

But it will also trigger dialog hiding, if you only need to recognize tap gestures, consider using `GestureDetector` on provided widget.

**Comment by Apollo108** [comment]
Also, I noticed strange behavior for top-positioned dialogs - I have to add direction: position == EasyDialogPosition.top ? VerticalSlideDirection.down : VerticalSlideDirection.up, otherwise it will be sliding from the bottom (by default) during the appearance and hiding, and it looks weird. For bottom-positioned - it's fine

**Comment by feduke-nukem** [comment]
> Also, I noticed strange behavior for top-positioned dialogs - I have to add `direction: position == EasyDialogPosition.top ? VerticalSlideDirection.down : VerticalSlideDirection.up`, otherwise it will be sliding from the bottom (by default) during the appearance and hiding, and it looks weird. For bottom-positioned - it's fine

You have full control over your dialogs, that's it.

If you want your dialog slide from bot to top or vice versa then you should provide relevant parameters

**Comment by Apollo108** [comment]
Thank you for the awesome package and rapid response!

**Comment by feduke-nukem** [comment]
> Thank you for the awesome package and rapid response!

You are welcome
