### ISSUE TITLE
[Feature]: Precise positioning of a dialog

### ISSUE THREAD

**Issue by DevTello** [feduke-nukem/flutter_easy_dialogs#23]
### What is your idea?

Hi, trying to make a minimized video player using this package, would be nice to be able to position a dialog precisely on the screen.
P.S.: is it possible to make it draggable also, or did I choose the wrong instrument for my purpose?) If yes, maybe you have an idea, where to look...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by feduke-nukem** [comment]
Hello @DevTello 

It is impossible to use this package in that way for now but it is a really good feature to implement.

I will to release it in a week or two

**Comment by DevTello** [comment]
Thank you very much, good sir! You always respond so fast, it's amazing! Be healthy and wealthy)

**Comment by feduke-nukem** [comment]
Hello, @DevTello 

You may try it out in the 3.2.0 version.

Just apply `draggable()` operator to your dialog like so:

```dart
final content = Container(
  height: 150.0,
  color: Colors.blue[900],
  alignment: Alignment.center,
  child: Text(
    _selectedPosition.name,
    style: const TextStyle(
      color: Colors.white,
      fontSize: 30.0,
    ),
  ),
);

content.positioned().draggable().show();
``` 

<div style="display:flex; flex-wrap:wrap;">
    <a style="flex:1;">
        <img src="https://github.com/feduke-nukem/flutter_easy_dialogs/assets/72284940/319d79d1-a744-4c6b-96ad-4c20ce07dabe" width="170"/>
    </a>
</div>
