### ISSUE TITLE
[Question]: Animation for showing/hiding a dialog

### ISSUE THREAD

**Issue by DevTello** [feduke-nukem/flutter_easy_dialogs#25]
### What is your question?

How do I set up an animation for showing/hiding a dialog?

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by DevTello** [comment]
Well, I need to set a Duration of showing and fading of a dialog, I managed to set up only `decoration: const EasyDialogAnimation.fade()`

**Comment by feduke-nukem** [comment]
> Well, I need to set a Duration of showing and fading of a dialog, I managed to set up only `decoration: const EasyDialogAnimation.fade()`

Each dialog has a property named `animationConfiguration` of type `EasyDialogAnimationConfiguration`. Every applied animation is working according to this.

To be able to configure durations independently you could create your own custom `EasyDialogAnimation`.

**Comment by DevTello** [comment]
`animationConfiguration:
          const EasyDialogAnimationConfiguration.bounded(
        duration: Duration(seconds: 1),
        reverseDuration: Duration(seconds: 1),
      ),`
forward duration plays 2x faster for me than reverseDuration, given they have the same Duration) is this the case for you?

**Comment by DevTello** [comment]
Sorry for the delay, I'm overloaded a bit. Will do as soon as I can)

**Comment by DevTello** [comment]
Here you go. Subjectively these 2 sec are perceived as 1.

`import 'package:flutter/material.dart';
import 'package:flutter_easy_dialogs/flutter_easy_dialogs.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
      builder: FlutterEasyDialogs.builder(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  EasyDialog? _dialog;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('Flutter Demo Home Page'),
        ),
        body: Center(
          child: MaterialButton(onPressed: showDialog, child: Text('Show')),
        ));
  }

  Future<void> showDialog() async {
    _dialog?.hide();
    _dialog = FullScreenDialog(
      animationConfiguration: const EasyDialogAnimationConfiguration.bounded(
        //plays 2x faster than reverseDuration for some reason
        duration: Duration(milliseconds: 2000),
        reverseDuration: Duration(milliseconds: 1000),
      ),
      decoration: const EasyDialogAnimation.fade(),
      content: Scaffold(
        body: SafeArea(
          child: Placeholder(child: Center(child: MaterialButton(onPressed: hideDialog, child: Text('Hide')))),
        ),
      ),
    )..show();
  }

  void hideDialog() {
    _dialog?.hide();
    _dialog = null;
  }
}
`

**Comment by DevTello** [comment]
Android 10

**Comment by DevTello** [comment]
Here is the link to the playground: https://flutlab.io/editor/bdca479b-172a-4311-81ef-fd0efc871343

**Comment by feduke-nukem** [comment]
> Here is the link to the playground: https://flutlab.io/editor/bdca479b-172a-4311-81ef-fd0efc871343

Thanks.

I will take a close look as soon as possible.

**Comment by feduke-nukem** [comment]
> Here is the link to the playground: https://flutlab.io/editor/bdca479b-172a-4311-81ef-fd0efc871343

Try to provide `Curves.linear` into ` const EasyDialogAnimation.fade(curve: Curves.linear)`.

The default curve is adding described "slow" behaviour.

**Comment by feduke-nukem** [comment]
> thanks, it helped, but not quite obvious)

Probably I should set all curves as `Linear` by default.
