### ISSUE TITLE
[Question]: Add example code

### ISSUE THREAD

**Issue by muneebshahzad95** [feduke-nukem/flutter_easy_dialogs#26]
### What is your question?

Please add some example code in plugin documentation.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by feduke-nukem** [comment]
Hello @muneebshahzad95 

There are examples in the topics section:

- [Dialogs](https://pub.dev/documentation/flutter_easy_dialogs/latest/topics/Dialogs-topic.html)
- [Decorations](https://pub.dev/documentation/flutter_easy_dialogs/latest/topics/Decorations-topic.html)

Also there are [App examples](https://github.com/feduke-nukem/flutter_easy_dialogs/tree/main/example/lib)
