### ISSUE TITLE
[Feature]: Multiple dialogs at a time

### ISSUE THREAD

**Issue by DevTello** [feduke-nukem/flutter_easy_dialogs#27]
### What is your idea?

**Is there a possibility of showing more than one dialog at a time?**
I noticed that a dialog of each type holds the hardcoded identifier, and when I'm trying to open another dialog of the same type, the prev one gets closed...
If that's possible, would have been nice to have user-defined ids + API to understand which one is visible and which is not.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by feduke-nukem** [comment]
Hello @DevTello.

Sure, why not.

Will implement that soon.

**Comment by DevTello** [comment]
Thanks, you're the best)

**Comment by feduke-nukem** [comment]
You may try it in 4.0.0 version https://pub.dev/packages/flutter_easy_dialogs @DevTello

**Comment by DevTello** [comment]
OMG, thanks, you're so fast)

**Comment by dragongesa** [comment]
fullscreen dialog id always => '\$FullScreenDialog', maybe you missing to add the id into fullscreen dialog
