### ISSUE TITLE
Missing id argument in extension dialogs method

### ISSUE THREAD

**Issue by feduke-nukem** [feduke-nukem/flutter_easy_dialogs#29]
fullscreen dialog id always => '\$FullScreenDialog', maybe you missing to add the id into fullscreen dialog

_Originally posted by @dragongesa in https://github.com/feduke-nukem/flutter_easy_dialogs/issues/27#issuecomment-2227397878_

**Comment by dragongesa** [comment]
![image](https://github.com/user-attachments/assets/e067880e-b244-4c44-ba64-c66d4c673b97)

check on line ```790``` on `lib/src/core/easy_dialogs_controller.dart` supposed to have id parameter on there i guess

**Comment by dragongesa** [comment]
Thankyou, i hope this fixed asap 👍🏻

**Comment by feduke-nukem** [comment]
@dragongesa 4.0.1 version has been published. You are welcome to try it

**Comment by dragongesa** [comment]
never see repo owner this fast to fixed issue 😮

thankyou sir, i will try it
